-- phpMyAdmin SQL Dump
-- version 4.5.4.1deb2ubuntu2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: May 11, 2018 at 05:46 PM
-- Server version: 5.7.22-0ubuntu0.16.04.1
-- PHP Version: 7.1.17-1+ubuntu16.04.1+deb.sury.org+1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `webservice`
--

-- --------------------------------------------------------

--
-- Table structure for table `exam`
--

CREATE TABLE `exam` (
  `quiz_id` int(11) NOT NULL,
  `exam_number` int(11) NOT NULL,
  `exam_question` varchar(700) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `exam_answer1` varchar(255) NOT NULL,
  `exam_answer2` varchar(255) NOT NULL,
  `exam_answer3` varchar(255) NOT NULL,
  `exam_answer4` varchar(255) NOT NULL,
  `exam_correct` varchar(255) NOT NULL,
  `exam_reason` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `exam`
--

INSERT INTO `exam` (`quiz_id`, `exam_number`, `exam_question`, `exam_answer1`, `exam_answer2`, `exam_answer3`, `exam_answer4`, `exam_correct`, `exam_reason`) VALUES
(2, 1, 'Which pair of words has the different vowel sound?', 'wet – vet', 'cake – take', 'king - kind', 'wish – wing', 'king - kind', 'อ่านออกเสียงแตกต่างกัน king=คิง kind=คาย'),
(2, 2, 'Which word starts with the same sound as “useful”?', 'unit', 'ugly', 'uncle', 'upset', 'unit', 'useful (ยูสฟูว) อ่านออกเสียงขึ้นต้นด้วย ยู เช่นเดียวกับ unit (ยูนิต) ที่อ่านออกเสียงขึ้นต้นด้วย ยู\r\n'),
(2, 3, 'You want someone to take a photo for you. What would you say to him?', 'Can I take a photo?', 'May I take a photo of you?', 'Do you want to take a photo?', 'Could you take a photo of me?', 'Could you take a photo of me?', 'โจทย์ต้องการให้เราขอคนให้คนอื่นช่วยถ่ายรูปให้กับเราซึ้งตรงกับคำตอบ Could you take a phpto of me?\r\n'),
(2, 4, '"At school \r\nWanida: ____________\r\nTeacher: Hi, Wanida, you come very early today."', 'Good luck.', 'Who are you?', 'Good morning.', 'How do you do?', 'Good morning.', 'จากโจทย์ต้องการประโยคทักทาย ซึ่งตรงกับคำตอบ Good morning.\r\n'),
(2, 5, '"Irene: How often do you wash your clothes?\r\nAlice: __________ I usually do it every Saturday."', 'Every day.', 'Once a week.', 'Twice a month.', 'Six times a year.', 'Once a week.', 'จากโจทย์ Alice ตอบว่า Every Saturday. ซึ่งมีความหมายว่าอาทิตย์ละครั้ง (ทุกวันเสาร์)\r\n'),
(2, 6, '"Ping: Do you like that movie?\r\nKim: __________ It’s amazing."', 'Yes, I do.', 'Yes, I am.', 'No, I don’t.', 'No, I’m not.', 'Yes, I do.', 'โจทย์ถามขึ้นต้นมาด้วย Do ต้องตอบว่า Do และท้ายประโยคตามด้วย Amazing ซึ่งเป็นสิ่งดี\r\n'),
(2, 7, '"Joe: What subject do you like most?\r\nJim: English. It’s fun.\r\nJoe: __________ A lot of foreigners visit our province, and I like talking to them."', 'Me, too.', 'Not for me.', 'Me, neither.', 'Neither do I.', 'Me, too.', 'เนื่องจากคำตอบของ Joe คล้อยตามกับคำตอบของ Jim จึงต้องตอบ Me, too.\r\n'),
(2, 8, '"At the book shop\r\nJonathan: __________\r\nShopkeeper: Twenty five baht."', 'How long is it?', 'How much is it?', 'How often do you read?', 'How many books are there?', 'How much is it?', 'เนื่องจาก Shopkeeper ตอบเป็นราคา Jonathan จึงต้องถาม How mush is it?\r\n'),
(2, 9, '"Situation : A teacher talks to the students, “Please do the role play in pairs”.\r\nWhat should the students do?"', 'Two students play a game.', 'Two students do the role play.', 'Each student plays a game.', 'Each student does the role play.', 'Two students do the role play.', 'pairs มีความหมายว่า เป็น คู่\r\n'),
(2, 10, '"\r\nHow to make “Apple juice”\r\n     1. Finally, pour it into a glass. Enjoy!\r\n     2. Then, add salt and syrup.\r\n     3. First, chop an apple into small pieces.\r\n     4. After that, blend it until mix well.\r\n     5. Next, put the pieces into the blender.\r\n\r\nWhich one is in the correct order?"', '3-2-5-4-1', '3-5-2-4-1', '3-4-5-2-1', '3-5-4-2-1', '3-5-2-4-1', 'คำนำหน้าขอแต่ละประโยคจะเป็นตัวบอกลำดับ'),
(2, 11, '"Read the passage and answer the questions.\r\n     Peter is going to visit his friend. He buys two pieces of cake for him. Each piece of cake is fifteen baht.\r\n\r\nWhere should he buy cakes?"', 'At a bakery.', 'At a grocery.', 'At a fruit stands.', 'At his friend’s house.', 'At a bakery.', 'Cake ต้องซือที่ Bakery'),
(2, 12, '"Read the conversation and answer the questions.\r\nAt school\r\nMary : Do you have any pets?\r\nKate : Yes, I have a small dog.\r\nMary : What kind of dog is it?\r\nKate : It is a puddle. Do you have any pets at home?\r\nMary : Yes, I have two cats. They can catch rats very well. What can your dog do?\r\nKate : It can sit, shake hands and roll over.\r\n\r\nWhich sentence is true?"', 'Kate has two cats.', 'Mary has a small dog.', 'Mary’s pets can catch rats very well.', 'Kate’s pet can sit and catch rats very well.', 'Mary’s pets can catch rats very well.', 'สัตว์เลี้ยงของ Mary เป็น แมวจึงจับแมวได้เก่ง'),
(2, 13, '"Read the conversation and answer the questions.\r\nAt school\r\nMary : Do you have any pets?\r\nKate : Yes, I have a small dog.\r\nMary : What kind of dog is it?\r\nKate : It is a puddle. Do you have any pets at home?\r\nMary : Yes, I have two cats. They can catch rats very well. What can your dog do?\r\nKate : It can sit, shake hands and roll over.\r\n\r\nWhich sentence is true?"', 'Pets.', 'Dogs.', 'Cats.', 'Rats.', 'Pets.', 'ทั้ง Cat และ Dog ล้วนเป็น Pets'),
(2, 14, '"Tom and Bob are friends.\r\nTom : Do you have any brothers or sisters?\r\nBob : I have one brother and one sister. And you?\r\nTom : I don’t have any brothers or sisters. __________."', 'I am the only child.', 'I have one sister.', 'I have one brother.', 'I am the favorite child.', 'I am the only child.', 'Tom บอกแล้วว่าไม่มีทั้งพี่ทั้งน้องจึงเป็นลูกคนเดียว (only child)\r\n'),
(2, 15, '"Harry and Julia are in the classroom.\r\nHarry : Our new English teacher comes to teach us today.\r\nJulia : __________.\r\nHarry : She’s quite tall and beautiful."', 'What does she like?', 'What does she look like?', 'What is she looking at?', 'What is she looking for?', 'What does she look like?', 'คำตอบของ Harry ตอบเป็นลักษณะรูปร่าง คำถามจึงต้องตอบเป็น look like?'),
(2, 16, '"Bee : You look __________ today. Why?\r\nAmy : I am the winner of English Speech Contest."', 'angry', 'tried', 'happy', 'sad', 'happy', 'Amy ชนะ จึงต้องรู้สึก Happy'),
(2, 17, '"Situation : Tom is driving a car. Then the traffic light turns red.\r\n\r\nWhen he sees the red light, what should he do?"', 'Go straight on.', 'Stop at the traffic light.', 'Prepare to go.', 'Park at the road side.', 'Stop at the traffic light.', 'ไฟแดง ต้องหยุดรถที่สัญญาณไฟ\r\n'),
(2, 18, '"Situation : In a scout camp.\r\nTeacher : Are you ready to go?\r\nBetty : No, I don’t t think so.\r\nTeacher : Why?\r\nBetty : We’re tired. __________."', 'We’re glad', 'We’re happy', 'We need some drinks', 'We want to run', 'We need some drinks', 'เนื่องจาก Betty เหนื่อย จึงต้องการน้ำ'),
(2, 19, 'What free time activity?', 'Go to school', 'Shopping', 'Write the report', 'Do homework', 'Shopping', 'ต้องเป็นกิจกรรมที่ทำได้ยามว่าง ซึ่งก็คือ shopping'),
(2, 20, 'Hurry up! The train ………… .', 'comes', 'came', 'is coming', 'come', 'is coming', 'Hurry up แสดงว่าเกิดขึ้นปัจจุบัน จึงต้องใช้ verb ing'),
(3, 1, '"Ann : The weather is very hot. Let’s go to the beach!\r\nBeth : _______ I love to swim in the sea."', ' That’s a good idea.', 'That sounds dangerous.', 'That’s very kind of you.', 'That seems very unhappy.', ' That’s a good idea.', 'คำตอบของ Beth ตอบว่า I love to swim จึงต้องคล้อยตามเห็นด้วย'),
(3, 2, '"John : What do you like to do in your free time?\r\nJane : I like reading and watching TV. __________\r\nJohn : I collect stamps."', 'How are you?', 'How about you?', 'what do you do?', 'What are you doing?', 'How about you?', 'คำตอบของ John ตอบแบบธรรมดา ไม่มี Tense ช่วย จึงต้องถาม How about you ?'),
(3, 3, '"Peter : I visited my grandparents in Khonkaen last weekend.\r\nMark : Great! _____________\r\nPeter : I went shopping and had dinner with them."', 'How did you go back?', 'What did you do there?', 'When did you go shopping?', 'Where did you have dinner?\r\n', 'What did you do there?', 'คำตอบของ Peter ตอบด้วย went ซึ่งเป็น tense pass con. จึงต้องถามด้วย did'),
(3, 4, '""On the phone\r\nMetha : Please ask John to call back Metha.\r\nNancy : __________, please.\r\nMetha : Metha, M-E-T-H-A. Thank you."\r\n', 'Speak softly', 'See you later', 'Say your name again.', 'Send your telephone number', 'Say your name again.', 'คำตอบของ Metha ทวนชื่อตัวเองอีกรอบ '),
(3, 5, '"At the party\r\nFrank : Joey, do you know that song? What’s the name?\r\nJoey : _________, what did you say?\r\nFrank : The name of the song! What is it?"\r\n"\r\n', 'Sorry', 'Certainly', 'Not at all', 'My pleasure', 'Sorry', 'Frank ต้องทวนคำถาม แสดงให้เห็นว่า Joey ไม่ได้ยินคำถามตอนแรก จึงต้องขอให้พูดอีกที'),
(3, 6, '"Situation : Tom is driving a car. Then the traffic light turns red.\r\nWhen he sees the red light, what should he do?"', 'Go straight on.', 'Stop at the traffic light.', 'Prepare to go.', 'Park at the road side.', 'Stop at the traffic light.', 'ไฟแดง ต้องหยุดรถที่สัญญาณไฟ'),
(3, 7, '"Jane : Mom, I’m going out.\r\nMother : Look, the sky is dark. Take an umbrella with you.\r\nJane : O.K. Thank you.\r\n\r\nWhat is the weather like?"', 'It’s snowy.', 'It’s cold.', 'It’s cloudy.\r\n', 'It’s windy.', 'It’s cloudy.', 'ไฟแดง ต้องหยุดรถที่สัญญาณไฟ'),
(3, 8, '"Read the passage and answer the questions.\r\n     Susan is ten years old. Bell is two years older than Susan. Tom is four years younger than Bell. Eddy is Tom’s younger brother.\r\nWho is the youngest?"\r\n', 'Bell', 'Susan', 'Tom', 'Eddy', 'Eddy', 'เมฆสีดำแสดงว่าฟ้าครึ้ม'),
(3, 9, '"Read the passage and answer the questions.\r\n     Susan is ten years old. Bell is two years older than Susan. Tom is four years younger than Bell. Eddy is Tom’s younger brother.\r\nWhich sentence is true?"', 'Eddy is a girl.', 'Bell is the oldest.', 'Susan is Eddy’s sister.', 'Susan is younger than Tom.', 'Bell is the oldest.\r\n', 'Susan อายุ 10 ปี Bell แก่กว่า Susan 2 ปี จึงอายุ 12 แต่ Tom อายุน้อยกว่า Bell 4 ปี จึงอายุ 8 ปี แต่ Eddyเป็นน้อง Bell จึงอายุมากสุด\r\n'),
(3, 10, '"Situation : In a scout camp.\r\nTeacher : Are you ready to go?\r\nBetty : No, I don’t t think so.\r\nTeacher : Why?\r\nBetty : We’re tired. __________."\r\n', 'We’re glad', 'We’re happy', 'We need some drinks', 'We want to run', 'We need some drinks\r\n', 'เนื่องจาก Betty เหนื่อย จึงต้องการน้ำ'),
(3, 11, '"At a mini mart.\r\nShopkeeper : Good evening. Can I help you?\r\nNid : Yes. Give me a dozen of eggs and two bottles of milk.\r\nShopkeeper : Here they are.\r\nNid : __________\r\nShopkeeper : They’re 150 baht."', 'How much do you want?', 'How much are they?', 'How much is it?.', 'How much do you work?', 'How much are they?\r\n', 'Shopkeeper ตอบเป็น They re จึงต้องถาม How much are they?'),
(3, 12, '"Read the conversation and answer the questions.\r\nAt school\r\nMary : Do you have any pets?\r\nKate : Yes, I have a small dog.\r\nMary : What kind of dog is it?\r\nKate : It is a puddle. Do you have any pets at home?\r\nMary : Yes, I have two cats. They can catch rats very well. What can your dog do?\r\nKate : It can sit, shake hands and roll over.\r\n\r\nWhich sentence is true?"\r\n', 'Kate has two cats.', 'Mary has a small dog.', 'Mary’s pets can catch rats very well.', 'Kate’s pet can sit and catch rats very well.', 'Mary’s pets can catch rats very well.\r\n', 'สัตว์เลี้ยงของ Mary เป็น แมวจึงจับแมวได้เก่ง'),
(3, 13, '"Your friend asks you what you think about his new telephone.\r\nYou say : __________"\r\n', 'Is it yours?', 'I also have one.', 'It’s nice.', 'Can I use it?', 'It’s nice.\r\n', 'It s nice เป็นคำตอบที่เหมาะสมกว่า I also have one'),
(3, 14, '"Joe : There’s a new Japanese restaurant on the corner.\r\nMike : Really? Have you tried it?\r\nJoe : Of course, I went there yesterday.\r\nMike : How was it?\r\nJoe : __________."\r\n', 'It isn’t far from here', 'My friend is a waiter there', 'You can walk there', 'The food is good and cheap', 'The food is good and cheap\r\n', 'คำถามของ Mike ถามว่าร้านเป็นยังไง จึงต้องตอบ The food is good and cheap '),
(3, 15, '"Harry and Julia are in the classroom.\r\nHarry : Our new English teacher comes to teach us today.\r\nJulia : __________.\r\nHarry : She’s quite tall and beautiful."\r\n', 'What does she like?', 'What does she look like?', 'What is she looking at?', 'What is she looking for?', 'What does she look like?\r\n', 'คำตอบของ Harry ตอบเป็นลักษณะรูปร่าง คำถามจึงต้องตอบเป็น look like?'),
(3, 16, '"Bee : You look __________ today. Why?\r\nAmy : I am the winner of English Speech Contest."\r\n', 'angry', 'tried', 'happy', 'sad', 'happy\r\n', 'Amy ชนะ จึงต้องรู้สึก Happy'),
(3, 17, '"There / kinds / are / teachers / school / our / in / many\r\nWhich sentence is correct?"\r\n', 'There are many teachers kinds in our school.', 'There are many kinds teachers in our school', 'There are kinds many teachers in our school.\r\n', 'There are teachers many kinds in our school.', 'There are many kinds teachers in our school.', 'คำตอบถูกต้องตาม Grammar'),
(3, 18, '"yesterday / She / doctor / to / went / the / see\r\nWhich sentence is correct?"', 'She went to see the doctor yesterday.', 'The doctor went to see she yesterday.', 'She went yesterday see to the doctor.\r\n', 'Yesterday to see the doctor she went.', 'She went to see the doctor yesterday.', 'คำตอบถูกต้องตาม Grammar'),
(3, 19, 'Which word is pronounced differently? It is “…………”\r\n', 'briefed', 'needed', 'talked', 'stopped', 'needed', 'เป็นคำเดียวที่อ่านสองพยางค์'),
(3, 20, 'Which word is pronounced “ed” at the end. It is “…………”\r\n', 'wanted', 'robbed', 'kissed', 'watched', 'wanted', 'อ่านว่า ว้อนเต็ด'),
(4, 1, '"Which underlined word is not correct?\r\nSam’s mother go to London last week."\r\n', ' ’s', 'go', 'to', 'last', '’s', '\'หากใส่ \'s ที่ระหว่าง Sam กับ mother จะกลายเป็นว่า Sam is mother\''),
(4, 2, '"Ben : I don’t like math. It is so hard.\r\nAlice : No, it isn’t. It’s easy.\r\nBen : __________. I don’t like numbers."', 'So am I.', 'So do I.', 'Not at all.', 'Not for me.', 'Not for me.', '\'คำตอบ ของ Ben ยังคงบอกไม่ชอบ I don\'t like numbers ซึ่งยังไม่เห็นด้วย\' '),
(4, 3, 'A: What do you like to do in your free time?   B : ___________________.\r\n', 'I\'m talking about my computer games.', 'Only in the shower.', 'I can\'t play the guitar.', 'I like to draw a picture.\r\n', 'I like to draw a picture.', 'เป็นคำตอบที่ถูก Grammar'),
(4, 4, '"I like to ...... foot ball. Fill in the gap to compleat the sentense.\r\nก."', 'play', 'read', 'do', 'is', 'play', 'foot ball ต้อง play'),
(4, 5, 'What free time activity?', 'Go to school', 'Shopping', 'Write the report', 'Do homework', 'Shopping', 'ต้องเป็นกิจกรรมที่ทำได้ยามว่าง ซึ่งก็คือ shopping'),
(4, 6, 'What does Sarah do in her free time?', 'She does her homework.', 'She do her homework.', 'She did her homework\r\n', 'non of above', 'She do her homework.', 'คำถามจริงๆ คือ Sarah do ต้องตอบ do'),
(4, 7, 'Where did you go last night?', 'I didn\'t went home.', 'I didn\'t like it.', 'I went home.', 'non of above', 'Me, too.', 'เนื่องจากคำตอบของ Joe คล้อยตามกับคำตอบของ Jim จึงต้องตอบ Me, too.'),
(4, 8, 'Does you friend like hot chocolate?\r\n', 'No, he don\'t.', 'No, he doesn\'t.', 'No, he does.', 'non of above', '\'No, he doesn\'t.\'', 'ถามว่า Does ต้องตอบ Does กรณีปฏิเศธใช้ doesn\'t'),
(4, 9, 'Did your dog slept well?', 'Yes, he does.', 'Yes, he did.', 'Yes, he does slept.', 'non of above', 'Yes, he did.\r\n', 'ถาม Did ตอบ Did'),
(4, 10, 'What is his mother doing?\r\n', 'He is cooking in the kitchen.', 'She is cooking in the kitchen.', 'She cooks in the kitchen.', 'non of above', 'She is cooking in the kitchen.\r\n', 'ถามด้วย Verb ing ต้องตอบ ing'),
(4, 11, 'My house is ………… the bank and the school.\r\n', 'between', 'among', 'behind', 'in front of.', 'between', 'between ใช้เชื่อมระหว่างสถานที่สองสถานที่'),
(4, 12, 'Bob ………… in the badminton tournament yesterday.\r\n', 'will lose', 'lost', 'lose', 'losing', 'lost\r\n', 'yesterday ต้องใช้ verb 2'),
(4, 13, 'Hurry up! The train ………… .\r\n', 'comes', 'came', 'is coming', 'come', 'is coming', 'Hurry up แสดงว่าเกิดขึ้นปัจจุบัน จึงต้องใช้ verb ing'),
(4, 14, 'Please hurry, Tom. We ………… late.\r\n', 'will', 'will come', 'are', 'will be', 'will be\r\n', 'ตาม Grammar We will be late ใช้ตามนี้'),
(4, 15, 'Did your father ………… those flowers?\r\n', 'water', 'waters', 'watered', 'watering', 'water\r\n', 'เนื่องจาก มี Did เป็น Verb หลักแล้ว water จึงไม่ต้องมี verb อะไรช่วย'),
(4, 16, 'Next holiday, I’m going to go camping in the ………… .\r\n', 'ocean', 'beach', 'river', 'mountain', 'mountain\r\n', 'การตั้ง Camp ต้องตั้งที่ ภูเขา '),
(4, 17, '"There / kinds / are / teachers / school / our / in / many\r\nWhich sentence is correct?"\r\n', 'There are many teachers kinds in our school.', 'There are many kinds teachers in our school', 'There are kinds many teachers in our school.\r\n', 'There are teachers many kinds in our school.', 'There are many kinds teachers in our school.', 'คำตอบถูกต้องตาม Grammar'),
(4, 18, 'We say “Close your eyes and make a wish” before you ………… .\r\n', 'get married', 'go out on Hallowee', 'blow out your birthday candles\r\n', 'go out on a date', 'blow out your birthday candles', 'ก่อนเป่าเค้กวันเกิดต้องหลับตาก่อนอธิษฐาน'),
(4, 19, 'Which word is pronounced differently? It is “…………”They speak English. They are ………… people.\r\n', 'speaking English', 'spoken English', 'English - speaking', 'English', 'English', 'คนอังกฤษต้อง English People'),
(4, 20, 'Thai people hope that the trouble with Thai Moslem in the south ………… .\r\n', 'will close', 'will be ended', 'is coming to an end', 'ended', 'will be ended', 'จากรูปประโยค แสดงให้เห็นถึงความหวัง ต้องใช้ future perfect tence will + be + v.2'),
(5, 1, '"At school:\r\nFonda:  Are you okay? You look sad.\r\nNancy:  I got an ‘F’ in Mathematics. I tried my best, but the exam was too difficult.\r\nFonda:  ________."\r\n', ' Don’t worry. Be happy', 'Don’t do that again', 'Don’t give up', 'Don’t tell anyone about this', 'Don’t give up', '\'Nancy ต้องการกำลังใจจึงมาบ่นกับ Fonda ประโยค Don\'t give up จึงเป็นประโยคที่เหมาะสม'),
(5, 2, '"At a seaside resort:\r\nSara:  What shall we do this afternoon?\r\nSonia:  ____(?)_____.\r\nSara:  Umm, it’s such a boring activity. Why don’t we go diving?\r\nSonia:  _________."\r\n', 'I still have no idea what to do', 'Let’s go sunbathing on the beach', 'I have to ask the rest of us first', 'Some of our friends won’t go diving with us', 'Let’s go sunbathing on the beach', 'คำตอบของ Sara เป็นตัวบอกว่า Sonia ตอบมาเป็นกิจกรรม '),
(5, 3, '"At a seaside resort:\r\nSara:  What shall we do this afternoon?\r\nSonia:  _________.\r\nSara:  Umm, it’s such a boring activity. Why don’t we go diving?\r\nSonia:  ____(?)_____."\r\n', 'I’m afraid we can’t', 'Because it’s dangerous', 'That sounds like a great idea', 'We still have enough of time to go\r\n', 'That sounds like a great idea', 'ช้อยอื่นๆใช่ tense ไม่ถูก Grammar'),
(5, 4, '"On the skytrain\r\nBill:  Excuse me. Have we met before?\r\nPloy:  I’m not sure. ____(?)____\r\nBill:  Yes. But that was a year ago. I’ve moved to a new company.\r\nPloy:  Oh. I see. Are you Bill?\r\nBill:  Yes.\r\nPloy:  _________. I’m ploy."\r\n', 'Did you work at QD Company?', 'Is your company near mine?', 'dDo you love your job?o', 'Can you remember my name?', 'Did you work at QD Company?', 'จากประโยคถัดไปของ Bill บอกว่าเขาย้ายไปอยู่บริษัทใหม่แล้ว'),
(5, 5, '"On the skytrain\r\nBill:  Excuse me. Have we met before?\r\nPloy:  I’m not sure. ________\r\nBill:  Yes. But that was a year ago. I’ve moved to a new company.\r\nPloy:  Oh. I see. Are you Bill?\r\nBill:  Yes.\r\nPloy:  ____(?)_____. I’m ploy."\r\n', 'You’re so kind', 'Good night Bill', 'It’s great we are friendsc', 'Nice to see you Bill', 'Nice to see you Bill', 'จากรูปประโยคแสดงให้เห็นว่าทั้งคู่พึ่งเคยเจอกัน '),
(5, 6, '"Directions: Read the situations and choose the best answer.\r\nSituation:\r\nDaughter: Mom, I’m going shopping with my friends at Chatuchak Weekend Market.\r\nMother: Beware of pickpockets. There are a lot of people there.\r\nDaughter: Thank you, mom.\r\nThe mother says that because __________."', 'she doesn’t want her daughter to go there', 'she wants her daughter to take good care of her purse\r\n', 'she doesn’t want to let her daughter go there alone\r\n', 'she wants her daughter to be careful when buying things', 'she wants her daughter to take good care of her purse', 'เนื่องจากโจทย์มีประโยค Beware of pickpockets ซึ่งแปลว่าพวกที่ชอบล้วงกระเป๋า\r\n'),
(5, 7, '"Directions: Read the situations and choose the best answer.\r\nSituation: Your friend asks your advice about how to lose weight.\r\nWhat will you say?"\r\n', 'You problem is that you weigh too much.', 'You need some good food for a happy life.\r\n', 'The best way to do is to exercise more.', 'If I were you, I’d gain some more weight.\r\n', 'The best way to do is to exercise more.', 'เป็นคำตอบที่ให้กำลังใจคนลดความอ้วนได้ดีที่สุด'),
(5, 8, '"Directions: Read the situations and choose the best answer.\r\nSituation: You want to ask your co-worker for his opinion about your presentation.\r\nWhat will you say?\r\n"', 'Am I good enough?', 'What do you think of it?', 'Is my presentation a good one?', 'Do you have any idea?\r\n', 'What do you think of it?', 'เป็นประโยคที่ใช้ถามความเห็นของผู้อื่น'),
(5, 9, '"\r\nDirections: Read the situations and choose the best answer.\r\nSituation: You friend won the first prize of lottery, but he lost all the lottery tickets.\r\nWhat will you say?\r\n"', 'Sorry to hear that.', 'Congratulations.', 'All the best.', 'You just have a bad day.', 'Sorry to hear that.', 'จากสถานการณ์ เพื่อนต้องการคำปลอบใจ'),
(5, 10, '"Directions: Read the situations and choose the best answer.\r\nSituation: A group of tourists has been looking for the Bangkok map for quite a while.\r\nWhat will you say?"\r\n', 'What are you doing?', 'Do you want to take a taxi?', 'Where are you from?', 'Can I help you?', 'Can I help you?\r\n', 'จะโจทย์ นักท่องเที่ยวต้องการความช่วยเหลือ'),
(5, 11, '"Directions: Choose the best answer.\r\n   A big bowl of milk and cereal can be a great way to start the day. (?)_______ breakfast cereals and snack bars contain nutrients _______ help our bodies stay _______ and healthy, but some of these foods _______ with too many vitamins and minerals.\r\n   According to a new study by the Environmental Working Group (EWG), this may by more harmful _______ helpful."\r\n', 'Many', 'Much', 'Few', 'Little', 'Few\r\n', 'ใช้ Few เพราะอาหารเช้าเป็น นามนับได้'),
(5, 12, '"Directions: Choose the best answer.\r\n   A big bowl of milk and cereal can be a great way to start the day. _______ breakfast cereals and snack bars contain nutrients (?)_______ help our bodies stay _______ and healthy, but some of these foods _______ with too many vitamins and minerals.\r\n   According to a new study by the Environmental Working Group (EWG), this may by more harmful _______ helpful."\r\n', 'who', 'which', 'whose', 'when', 'which\r\n', 'Which เป็นตัวเชื่อมประโยคที่นิยมใช้'),
(5, 13, '"Directions: Choose the best answer.\r\n   A big bowl of milk and cereal can be a great way to start the day. _______ breakfast cereals and snack bars contain nutrients_______ help our bodies stay  (?) _______ and healthy, but some of these foods _______ with too many vitamins and minerals.\r\n   According to a new study by the Environmental Working Group (EWG), this may by more harmful _______ helpful."\r\n', 'strength', 'strong', 'strongly', 'strengthen', 'strong', 'เป็นไปตามรูปประโยค'),
(5, 14, '"Directions: Choose the best answer.\r\n   A big bowl of milk and cereal can be a great way to start the day. _______ breakfast cereals and snack bars contain nutrients_______ help our bodies stay  _______ and healthy, but some of these foods  (?)_______ with too many vitamins and minerals.\r\n   According to a new study by the Environmental Working Group (EWG), this may by more harmful _______ helpful."\r\n', 'pack', 'packed', 'are packing', 'are packed', 'are packing\r\n', 'เป็นไปตามรูปประโยค'),
(5, 15, '"Directions: Choose the best answer.\r\n   A big bowl of milk and cereal can be a great way to start the day. _______ breakfast cereals and snack bars contain nutrients_______ help our bodies stay  _______ and healthy, but some of these foods  ______ with too many vitamins and minerals.\r\n   According to a new study by the Environmental Working Group (EWG), this may by more harmful __(?)______ helpful."\r\n', 'and', 'but', 'than', 'too', 'but\r\n', 'เป็นไปตามรูปประโยค'),
(5, 16, '"Directions: Choose the best answer.\r\n   A group of (?)_______ criminals have stolen 1.2 billion username and password combinations. It is the _______ known collection of stolen Internet credentials, according to a New York Times report.\r\n   Cyber security firm Hold Security ________ that the group of criminals collected personal information from 420,000 websites such as household names and small Internet sites. They _____ websites inside Russia as well as big companies in the U.S. and ________ countries. The firm cannot say exactly which websites were broken into."\r\n', 'Russia', 'Russian', 'Russians', 'Russian’s', 'Russians\r\n', 'Group of ต้องตามด้วยชนชาทนั้นๆ'),
(5, 17, '"Directions: Choose the best answer.\r\n   A group of _______ criminals have stolen 1.2 billion username and password combinations. It is the (?) _______ known collection of stolen Internet credentials, according to a New York Times report.\r\n   Cyber security firm Hold Security ________ that the group of criminals collected personal information from 420,000 websites such as household names and small Internet sites. They _____ websites inside Russia as well as big companies in the U.S. and ________ countries. The firm cannot say exactly which websites were broken into."\r\n', 'large', 'larger', 'largest', 'very large', 'largest', 'largest ไว้จบประโยค'),
(5, 18, '"Directions: Choose the best answer.\r\n   A group of _______ criminals have stolen 1.2 billion username and password combinations. It is the _______ known collection of stolen Internet credentials, according to a New York Times report.\r\n   Cyber security firm Hold Security  (?) ________ that the group of criminals collected personal information from 420,000 websites such as household names and small Internet sites. They _____ websites inside Russia as well as big companies in the U.S. and ________ countries. The firm cannot say exactly which websites were broken into."\r\n', 'found', 'was found', 'has been found\r\n', 'was finding', 'was found', 'เป็นไปตามรูปประโยค'),
(5, 19, '"Directions: Choose the best answer.\r\n   A group of _______ criminals have stolen 1.2 billion username and password combinations. It is the _______ known collection of stolen Internet credentials, according to a New York Times report.\r\n   Cyber security firm Hold Security   ________ that the group of criminals collected personal information from 420,000 websites such as household names and small Internet sites. They(?) _____ websites inside Russia as well as big companies in the U.S. and ________ countries. The firm cannot say exactly which websites were broken into."\r\n', 'hatched', 'hiked', 'hooked', 'hacked', 'hacked', 'เป็นไปตามรูปประโยค'),
(5, 20, '"Directions: Choose the best answer.\r\n   A group of _______ criminals have stolen 1.2 billion username and password combinations. It is the _______ known collection of stolen Internet credentials, according to a New York Times report.\r\n   Cyber security firm Hold Security ________ that the group of criminals collected personal information from 420,000 websites such as household names and small Internet sites. They _____ websites inside Russia as well as big companies in the U.S. and  (?) ________ countries. The firm cannot say exactly which websites were broken into."\r\n', 'other', 'others', 'another', 'one another', 'another', 'เป็นไปตามรูปประโยค'),
(6, 1, '"Directions: Choose the best answer.\r\n   When Wu Kai, a Harbin resident, looked (?)_______ her apartment window on Monday, she couldn’t see anything. At first, she thought it _______. Then she realized it was smog. Her husband left for work wearing a mask to _______ his mouth and nose and stop him from breathing in the pollution. His regular bus wasn’t out of service _______ the low visibility.\r\n   Many people ________ get around. Authorities in the city closed schools and some highways on Monday. Harbin’s Taiping International Airport canceled or delayed at least 40 flights."\r\n', 'at', 'out', 'down', 'in', 'at', 'เป็นไปตามรูปประโยค'),
(6, 2, '"Directions: Choose the best answer.\r\n   When Wu Kai, a Harbin resident, looked _______ her apartment window on Monday, she couldn’t see anything. At first, she thought it  (?)_______. Then she realized it was smog. Her husband left for work wearing a mask to _______ his mouth and nose and stop him from breathing in the pollution. His regular bus wasn’t out of service _______ the low visibility.\r\n   Many people ________ get around. Authorities in the city closed schools and some highways on Monday. Harbin’s Taiping International Airport canceled or delayed at least 40 flights."\r\n', 'snows', 'snowed', 'had snowed', 'was snowing', 'snowed', 'ประโยคข้างหน้าใช้ though it จึงต้องใช้ verb 2'),
(6, 3, '"Directions: Choose the best answer.\r\n   When Wu Kai, a Harbin resident, looked _______ her apartment window on Monday, she couldn’t see anything. At first, she thought it  _______. Then she realized it was smog. Her husband left for work wearing a mask to (?)_______ his mouth and nose and stop him from breathing in the pollution. His regular bus wasn’t out of service _______ the low visibility.\r\n   Many people ________ get around. Authorities in the city closed schools and some highways on Monday. Harbin’s Taiping International Airport canceled or delayed at least 40 flights."\r\n', 'cover', 'lower', 'close', 'lock\r\n', 'cover', 'เป็นไปตามรูปประโยค'),
(6, 4, '"Directions: Choose the best answer.\r\n   When Wu Kai, a Harbin resident, looked _______ her apartment window on Monday, she couldn’t see anything. At first, she thought it  _______. Then she realized it was smog. Her husband left for work wearing a mask to _______ his mouth and nose and stop him from breathing in the pollution. His regular bus wasn’t out of service (?)_______ the low visibility.\r\n   Many p1eople ________ get around. Authorities in the city closed schools and some highways on Monday. Harbin’s Taiping International Airport canceled or delayed at least 40 flights."\r\n', 'despite', 'even though', 'because of ', 'because', 'because', 'เป็นไปตามรูปประโยค\r\n'),
(6, 5, '"Directions: Choose the best answer.\r\n   When Wu Kai, a Harbin resident, looked _______ her apartment window on Monday, she couldn’t see anything. At first, she thought it  _______. Then she realized it was smog. Her husband left for work wearing a mask to _______ his mouth and nose and stop him from breathing in the pollution. His regular bus wasn’t out of service _______ the low visibility.\r\n   Many people (?)________ get around. Authorities in the city closed schools and some highways on Monday. Harbin’s Taiping International Airport canceled or delayed at least 40 flights."\r\n', 'must', 'mustn’t', 'could', 'couldn’t', 'couldn’t', 'เป็นไปตามรูปประโยค'),
(6, 6, '"Directions: Read the situations and choose the best answer.\r\nSituation:\r\nDaughter: Mom, I’m going shopping with my friends at Chatuchak Weekend Market.\r\nMother: Beware of pickpockets. There are a lot of people there.\r\nDaughter: Thank you, mom.\r\nThe mother says that because __________."\r\n', 'she doesn’t want her daughter to go there', 'she wants her daughter to take good care of her purse\r\n', 'she doesn’t want to let her daughter go there alone\r\n', 'she wants her daughter to be careful when buying things', 'she wants her daughter to take good care of her purse', 'เนื่องจากโจทย์มีประโยค Beware of pickpockets ซึ่งแปลว่าพวกที่ชอบล้วงกระเป๋า\r\n'),
(6, 7, '"Directions: Choose the correct answer which has the same meaning as the given sentence.\r\nTom is smarter than Big but not so smart as Paul."\r\n', 'Big is smarter than Paul', 'Paul is smarter than Tom\r\n', 'Big and Paul are smarter than Tom', 'Tom is the smarter\r\n', 'Paul is smarter than Tom', 'จากโจทย์ แปลว่า Tom ฉลากกว่า Big แต่ว่า ไม่ฉลาดเท่า Paul'),
(6, 8, '"Directions: Choose the correct answer which has the same meaning as the given sentence.\r\nJimmy was a fruit seller for 10 years."\r\n', 'Jimmy is now a fruit seller.', 'Jimmy has been selling fruits for 10 years.', 'Jimmy started selling fruits 10 years ago.', 'Jimmy is not a fruit seller anymore.\r\n', 'Jimmy is not a fruit seller anymore.', 'จากโจทย์ was แปลว่าเคยกระทำแต่ไม่กระทำอยู่ในปัจจุบัน'),
(6, 9, '"Directions: Choose the correct answer which has the same meaning as the given sentence.\r\nHenry’s favorite food is spaghetti."\r\n', 'Henry loves spaghetti more than other food.', 'Spaghetti is one of the dishes that Henry likes.', 'Henry loves spaghetti as well as other food.\r\n', 'Henry doesn’t mind eating spaghetti.', 'Henry loves spaghetti more than other food.', 'favorite แปลว่าโปรดที่สุดโปรดกว่าอันอื่น'),
(6, 10, '"Directions: Read the situations and choose the best answer.\r\nSituation: A group of tourists has been looking for the Bangkok map for quite a while.\r\nWhat will you say?"\r\n', 'What are you doing?', 'Do you want to take a taxi?', 'Where are you from?', 'Can I help you?', 'Can I help you?\r\n', 'จะโจทย์ นักท่องเที่ยวต้องการความช่วยเหลือ'),
(6, 11, '"\r\nDirections: Choose the correct answer which has the same meaning as the given sentence.\r\nHe forgot to bring an umbrella, so he got wet."\r\n', 'If he brings his umbrella, he won’t get wet.', 'Although he brought his umbrella, he got wet.', 'Before he got wet, he forgot to bring his umbrella.', 'He got wet because he forgot to bring his umbrella.', 'If he brings his umbrella, he won’t get wet.\r\n', 'ค่ำว่า so หมายถึงประโยคข้างหน้าส่งผลต่อประโยคหลัง'),
(6, 12, '"Directions: Choose the correct answer which has the same meaning as the given sentence.\r\nEither Thomas or Linda will hold a party."\r\n', 'Both of them will hold a party.', 'One of them will hold a party.', 'None of them will hold a party.', 'Thomas not Linda will hold a party.', 'One of them will hold a party.\r\n', 'or คือให้เลือกคนใดคนหนึ่ง'),
(6, 13, '"Error Recognition\r\nDirections: Choose the answer which is grammatically incorrect.\r\nNot (1) drinking enough water can lead (2) to health problems such as headaches, (3) poorly physical performance, and (4) more serious issues."\r\n', 'drinking ', 'to', 'poorly ', 'more', 'drinking ', 'ผิดแกรมม่า'),
(6, 14, '"Error Recognition\r\nDirections: Choose the answer which is grammatically incorrect.\r\nNot (1) drinking enough water can lead (2) to health problems such as headaches, (3) poorly physical performance, and (4) more serious issues."\r\n', 'drinking ', 'to', 'poorly ', 'more', 'drinking \r\n', 'ผิดแกรมม่า'),
(6, 15, '"Error Recognition\r\nDirections: Choose the answer which is grammatically incorrect.\r\n(1) Heavy rainfall caused the river (2) to overflow and (3) raise to a record breaking (4) 43-feet crest."\r\n', 'Heavy', 'to overflow', 'raise ', '43-feet', 'raise \r\n', 'ผิดแกรมม่า'),
(6, 16, '"Error Recognition\r\nDirections: Choose the answer which is grammatically incorrect.\r\nAround 88 million Americans (1) whom don’t smoke, (2) including 54% of children (3) between the ages of 3 and 11 , are (4) exposed to secondhand smoke."\r\n', 'whom', 'including ', 'between ', 'exposed ', 'whom', 'ผิดแกรมม่า'),
(6, 17, '"Error Recognition\r\nDirections: Choose the answer which is grammatically incorrect.\r\nThe money (1) that the government collects from junk food taxes (2) will be put towards projects that (3) encouraging people to eat (4) healthy foods."\r\n', 'that', 'will be put', 'encouraging', 'healthy', 'that', 'ผิดแกรมม่า'),
(6, 18, '"Error Recognition\r\nDirections: Choose the answer which is grammatically incorrect.\r\nA school’s football season (1) often begins in (2) late summer when temperatures are still (3) high, so there (4) are a greater risk for heat stroke."\r\n', 'often', 'late', 'high\r\n', 'are', 'often', 'ผิดแกรมม่า'),
(6, 19, '"Directions: Choose the correct answer which has the same meaning as the given sentence.\r\nJimmy was a fruit seller for 10 years."\r\n', 'Jimmy is now a fruit seller.', 'Jimmy has been selling fruits for 10 years.', 'Jimmy started selling fruits 10 years ago.', 'Jimmy is not a fruit seller anymore.\r\n', 'Jimmy is not a fruit seller anymore.', 'จากโจทย์ was แปลว่าเคยกระทำแต่ไม่กระทำอยู่ในปัจจุบัน'),
(6, 20, '"Error Recognition\r\nDirections: Choose the answer which is grammatically incorrect.\r\nNot (1) drinking enough water can lead (2) to health problems such as headaches, (3) poorly physical performance, and (4) more serious issues."\r\n', 'drinking ', 'to', 'poorly ', 'more', 'drinking ', 'ผิดแกรมม่า'),
(7, 1, '"Directions: Choose the correct answers which have the same meaning as the given sentences.\r\nSince Susan moved to Florida in 2002, she hasn’t moved to any other place."\r\n', 'Susan is now in Florida.', 'Susan is not living in Florida now.', 'After 2002, Susan moved to Florida', 'Susan lived in Florida before she moved to another place.', 'Susan is now in Florida.\r\n', 'จาก she hasn\'t moved to any other place แปลว่ายังไม่ได้ย้ายไปที่ไหน'),
(7, 2, '"Directions: Choose the correct answers which have the same meaning as the given sentences.\r\nHad you studied harder, you would have passed the examination."\r\n', 'You will pass the examination if you study harder.', 'Although you studied harder, you didn’t pass the examination.', 'You didn’t pass the examination because you didn’t study harder.\r\n', 'You passed the examination because you studied harder.', 'You didn’t pass the examination because you didn’t study harder.\r\n', 'จากรูปประโยค แสดงว่าสอบตกไปแล้ว'),
(7, 3, '"Directions: Choose the correct answers which have the same meaning as the given sentences.\r\nOf the five students, Jack is the most intelligent."\r\n', 'Jack is as intelligent as the other four students.', 'The other four students are more intelligent than Jack.', 'The other four students are less intelligent than Jack.\r\n', 'Jack is the most intelligent student in the school.', 'The other four students are less intelligent than Jack.\r\n', 'Tho most แปลว่ามากที่สุด จากโจทย์ บอกว่า มากสุดในเด็กทั้งห้าคน'),
(7, 4, '"Directions: Choose the correct answers which have the same meaning as the given sentences.\r\nTim cannot drive, and neither can Tom."\r\n', 'Both Tim and Tom cannot drive.', 'Unlike Tim, Tom can drive.', 'Tim and Tom don’t want to be a driver.', 'Both Tim and Tom didn’t learn to drive.\r\n', 'Both Tim and Tom cannot drive.', 'neither แปลว่า ก็เช่นเดียวกับ\r\n'),
(7, 5, '"Directions: Choose the correct answers which have the same meaning as the given sentences.\r\nJohn was too young to join this program."\r\n', 'John was young, but he was able to join this program.', 'John was not able to join this program because he was not young enough.', 'John was young, so he was able to join this program.\r\n', 'John was not old enough to join this program.', 'John was not old enough to join this program.', 'was too young  แปลว่า ยังเด็กเกินไป'),
(7, 6, '"Error Recognition\r\nDirections: Choose the answer which is grammatically incorrect.\r\n     Eating too much salt increases your risk of develop high blood pressure (hypertension), which is a major risk factor for heart disease, kidney disease and stroke."\r\n', 'increases', 'develop', 'which is', 'for', 'increases', 'ผิดแกรมม่า'),
(7, 7, '"Error Recognition\r\nDirections: Choose the answer which is grammatically incorrect.\r\n     Einstein first became interesting in science when his father gave him a compass."\r\n', 'first', 'interesting', 'when', 'gave', 'interesting', 'ผิดแกรมม่า'),
(7, 8, '"Error Recognition\r\nDirections: Choose the answer which is grammatically incorrect.\r\n     Michael Faraday, who came from a very poor family, became one of the most greatest scientists in history."\r\n', 'who came', 'became', 'most', 'scientists', 'most', 'ผิดแกรมม่า'),
(7, 9, '"Error Recognition\r\nDirections: Choose the answer which is grammatically incorrect.\r\n     Technology not only enables students to access more and better resources and also provides faster and more versatile methods for gathering, sharing, and manipulating information."\r\n', 'not only', 'access', 'and', 'gathering', 'and', 'ผิดแกรมม่า'),
(7, 10, 'Error Recognition\r\nDirections: Choose the answer which is grammatically incorrect.\r\n     Millions of animals use in medical experiments each year, many of which are funded by taxpayer dollars and charitable donations.', 'Millions', 'use', 'year', 'many of which', 'many of which', 'ผิดแกรมม่า'),
(7, 11, '"Yes, I burst out ………… when I ………… .\r\n', 'laugh, saw his book.', 'to laugh, saw his picture', 'laugh, saw his picture', 'laughing, saw his book', 'laugh, saw his picture\r\n', 'v.to be มักตามด้วย คำเชื่อม และ หนังสือไม่ทำให้ขำได้'),
(7, 12, 'Look at ………… in the mirror!\r\n', 'you', 'yours', 'yourself', 'your', 'your', 'ตาม Grammar at'),
(7, 13, 'It’s ………… business if I do.\r\n', 'nobody ', 'nobody’s', 'of nobody ', 'nobody of', 'nobody ', 'มี \'s แล้ว เท่ากับ มี verb แล้วไม่ต้องมี verb ช่วยอีก'),
(7, 14, 'Barbie is ………… doll.\r\n', 'prettier ', 'the prettiest', 'pretty ', 'as pretty as', 'pretty ', 'จากรูปประโยค is ตามด้วย v.1'),
(7, 15, 'While I ………… for the bus I ………… two masked men running out.\r\n', 'waited, saw', 'am waiting, see', 'was waiting, saw ', 'was waiting, see', 'am waiting, see ', 'จากรูปประโยค is ตามด้วย v.to be + ving'),
(7, 16, 'While I ………… to open the door, someone ……… my shoulder and I jumped in surprise.\r\n', 'tried, touched', 'was trying, touched ', 'am trying, am touching ', 'am trying, touch ', 'am trying, touch', 'จากรูปประโยค is ตามด้วย v.to be + ving'),
(7, 17, 'Suda finds it necessary to water her flowers ………… .\r\n', 'two in a week', 'two times a week', 'twice a week', 'two in one', 'twice a week', 'เป็นไปตาม Grammar'),
(7, 18, 'Yes, I also like the ………… by Gibbs. He’s funny and he’s an excellent artist too.\r\n', 'cartoons', 'folk tales', 'fictions\r\n', 'documents', 'cartoons', 'artist ในรูปประโยคหลังเป็นตัวบ่งบอก'),
(7, 19, 'If only I ………… more money now, I could buy a new dress.\r\n', 'had', 'have', 'have had', 'had had', 'have', 'เป็นไปตาม Grammar'),
(7, 20, 'The workers wouldn’t have gone on strike if only the manager ………… more reasonable.\r\n', 'were ', 'had been', 'had ', 'have had', 'have had ', 'เป็นไปตาม Grammar'),
(8, 1, '"Directions: Read each situation and choose the BEST alternative.\r\nSituation: Pete has a financial problem and Mr. Thompson has approved a loan for him. Pete says:"\r\n', 'How nice of you to approve it!', 'I really appreciate your help.', 'What a kind man you are!', 'I think you’re a generous man. Thanks.', 'I really appreciate your help.\r\n', 'เนื่องจาก Pete มีปัญหา โดย Mr. Thompson ได้ให้ความช่วยเหลือ Pete จึงต้องพูดขอบคุณ\r\n'),
(8, 2, '"Directions: Read each situation and choose the BEST alternative.\r\nSituation: Lisa is visiting a sick colleague at the hospital. She says:"\r\n', 'Don’t worry. Make yourself at home.', 'Take it easy. Time flies.', 'Calm down. Take a rest for a while.', 'Get well soon. We miss you at the office.', 'Get well soon. We miss you at the office.\r\n', 'sick colleague แปลว่าเพื่อนร่วมงานที่ป่วย คำตอบที่ถูกต้องจึงต้องมี at the office.\r\n'),
(8, 3, '"Directions: Read each situation and choose the BEST alternative.\r\nSituation: Mrs. Green asks her daughter what her new roommate at the university dormitory is like. Her daughter says:"\r\n', 'She’s tall and slim.', 'She’s got long dark hair.', 'She’s friendly and cheerful.', 'She likes swimming and skiing.\r\n', 'She’s friendly and cheerful.', 'โจทย์ถามว่า what her new rommate at the university dormitory is like.ซึ่ง is like มีความหมายว่า มีลักษณะนิสัยอย่างไร\r\n'),
(8, 4, '"Directions: Read each situation and choose the BEST alternative.\r\nSituation: After dinner, Anna asks her friend if he enjoyed the food she prepared. Her friend says:"\r\n', 'It was wonderful. You’re a great cook.', 'Well, it looked good. But I’m on diet.', 'That’s well done. I do have a great time.', 'It appears delicious. I should be invited again.', 'It was wonderful. You’re a great cook.', 'คำตอบ It was wonderful. You’re a great cook.. เป็นคำตอบที่เหมาะสมที่สุดไม่โอเวอร์จนเกินไป ไม่แย่จนเกินไป\r\n'),
(8, 5, '"Directions: Read each situation and choose the BEST alternative.\r\nSituation: Kari invites Jenny to go to a concert. Jenny has to finish an assignment, so she says:"\r\n', 'I like that idea. I’ll make a decision.', 'That’s marvelous. I don’t want to go.', 'That’s fine. But sorry, it’s not possible for we.\r\n.', 'That sounds great. But I don’t think I can make it.', 'That sounds great. But I don’t think I can make it.\r\n', 'เนื่องจาก Jenny ยังทำงานของตัวเองไม่เสร็จ จึงคิดว่าไม่น่าจะไปด้วยได้ ดังนั้นควรตอบThat sounds great. But I don’t think I can make it.\r\n'),
(8, 6, '"Directions: Read each sentence and choose the alternative that BEST completes it.\r\nThe boy claimed that the pencil box belonged to him, but soon everybody found out that he___."\r\n', 'is lying', 'tells a lie', 'has told a lie', 'had told a lie.', 'has told a lie', 'เนื่องจากรูปประโยคทั้งหมด อยู่.ใน tense Past perfect con. จึงต้องตอบเป็น Past perfect con.\r\n'),
(8, 7, '"Directions: Read each sentence and choose the alternative that BEST completes it.\r\nThe little girl held her mother’s hand firmly ____ the other side of the street."\r\n', 'if they walk along', 'until they walked to', 'when they walk down', 'as they walked over', 'until they walked to\r\n', 'คำตอบ until they walked to เป็นคำตอบที่เข้ากับรูปประโยค\r\n'),
(8, 8, '"Directions: Read each sentence and choose the alternative that BEST completes it.\r\nWhy didn’t you give something to the taxi driver ____?"\r\n', 'who has brought your briefcase to you', 'whom your briefcase you brought to\r\n', 'who brought you your briefcase', 'that to you he brought your briefcase\r\n', 'who brought you your briefcase', 'who brought you your briefcase เป็นประโยคที่ถูกต้อง ที่แปลว่า คนที่เป็นคนเจอกระเป๋าของคุณ\r\n'),
(8, 9, '"Directions: Read each sentence and choose the alternative that BEST completes it.\r\nThe Boy Scouts had to take ____ to the camp, each carrying a heavy backpack."\r\n', 'a two-mile hike', 'a two miles hike', 'a two-miles’ hike', 'a hike in two miles', 'a two-mile hike', 'a two-mile hike ถูกต้องตามหลักแกรมม่า\r\n'),
(8, 10, '"Directions: Read each sentence and choose the alternative that BEST completes it.\r\nIt is required that the new Japanese student ____ in an extra English conversation course."\r\n', 'enroll', 'enrolled', 'will enroll', 'would enroll', 'enroll', 'enroll ถูกต้องตามหลักแกรมม่า'),
(8, 11, '"Directions: Read each sentence and choose the alternative that BEST completes it.\r\nThe customer wanted to know ___."\r\n', 'she could find a can of baked beans where', 'where could she find a can of baked beans\r\n', 'a can of baked beans was where she could find', 'where she could find a can of baked beans\r\n', 'where she could find a can of baked beans', 'where ต้องคนต้นประโยค ตามด้วย ประธาน(she) ตามด้วย verb ( could find)'),
(8, 12, '"Directions: Read each sentence and choose the alternative that BEST completes it.\r\nThe author wishes that _____ in an international journal the year before."\r\n', 'he publishes his article', 'he published his article', 'his article will be published\r\n', 'his article had been published', 'his article had been published', 'the year before. เป็นตัวบอกว่า เกิดขึ้นเมื่อปีก่อน ดังนั้นต้องใช้ Past perfect tense ในการตอบ'),
(8, 13, '"Directions: Read each sentence and choose the alternative that BEST completes it.\r\nEach kind of pet should be fed and ____ according to its individual requirements."\r\n', 'treat.', 'treated.', 'is to treat.', 'has treated.', 'treated.', 'should be fed fed เป็นช่องสอง ดังนั้นต้องตอบเป็น V.2 ของ treat ด้วย'),
(8, 14, '"Directions: Read each sentence and choose the alternative that BEST completes it.\r\nDr. Jackson, ____, displayed his scientific genius when he was still a boy of five."', 'university’s prominent scientist', 'universities’ prominent scientist', 'the prominent scientist of university', 'a prominent scientist of the university', 'a prominent scientist of the university', 'prominent scientist เป็นชื่อตำแหน่งต้องนำหน้าด้วย a'),
(8, 15, '"Directions: Read each sentence and choose the alternative that BEST completes it.\r\nAnybody who wants to lose weight must avoid diets ____ carbohydrates."\r\n', 'which contains', 'that contain', 'which contained', 'that are containing', 'that contain', 'จากรูปประโยค diets มีอยู่ใน carbohydrates ดังนั้นต้องใช้ that ที่เป็นตัวเชื่อม'),
(8, 16, '"Directions: Read each sentence and choose the alternative that BEST completes it.\r\nThe guide reminded the tourists what to take along with them, what to wear and ____."\r\n', 'where to meet the next morning', 'the next morning where to be met', 'where they will meet the next morning', 'where should they meet the next morning', 'where to meet the next morning\r\n', 'จากประโยคข้างหน้า what to wear ต้องตามด้วย where to meet'),
(8, 17, '"Directions: Read each sentence and choose the alternative that BEST completes it.\r\nI understand that ____ earlier, but I could not find your address."\r\n', 'I have sent you the letter', 'I might sent you the letter to you', 'the letter will be sent to you', 'I should have sent you the letter', 'I should have sent you the letter\r\n', 'ประโยคหลังเป็น could ประโยคหน้าต้องใช้ should'),
(8, 18, '"Directions: Read each sentence and choose the alternative that BEST completes it.\r\nAccording to the forecast, the people in this region will face a lot of rainstorms ___ May ___ August."\r\n', 'completely exhausted', 'exhausting completely', 'completely exhausting', 'complete exhausting\r\n', 'completely exhausted\r\n', 'after playing แสดงว่าเล่นเสร็จแล้ว ต้องตามด้วย completely ที่แปลว่าสำเร็จ และ v.2  exhausted'),
(8, 19, '"Directions: Read each sentence and choose the alternative that BEST completes it.\r\nThe teacher instructed the students to stop work on the exam, _____ on their desks before leaving the room."\r\n', 'to lay down their pencils, leave their paper', 'and lay down their pencils, leave their paper', 'lay down their pencils and to leave their paper\r\n', 'lay down their pencils and leave their paper\r\n', 'lay down their pencils and leave their paper', 'คำตอบเป็นการขึ้นตอนประโยคใหม่ จะไม่ขึ้นต้นด้วยคำเชื่อม และการเชื่อมด้วย and จะต้องเท่ากันทั้งประโยคหน้าและหลัง ไม่มี to ทั้งคู่');
INSERT INTO `exam` (`quiz_id`, `exam_number`, `exam_question`, `exam_answer1`, `exam_answer2`, `exam_answer3`, `exam_answer4`, `exam_correct`, `exam_reason`) VALUES
(8, 20, '"Directions: Read each situation and choose the BEST alternative.\r\nSituation: After dinner, Anna asks her friend if he enjoyed the food she prepared. Her friend says:"\r\n', 'It was wonderful. You’re a great cook.', 'Well, it looked good. But I’m on diet.\r\n', 'That’s well done. I do have a great time.', 'It appears delicious. I should be invited again.', 'It was wonderful. You’re a great cook.\r\n', 'คำตอบ It was wonderful. You’re a great cook.. เป็นคำตอบที่เหมาะสมที่สุดไม่โอเวอร์จนเกินไป ไม่แย่จนเกินไป'),
(9, 1, '"Student: What do I have to do if I want to withdraw from course?\r\nTeacher: If you want to _______ the course, you have to go to the college office."\r\n', 'do', 'drop', 'take', 'attend', 'drop', 'การ withdraw หรือถอนในมหาวิทยาลัยใช้คำว่า drop'),
(9, 2, '"Tom: Are you going to phone Patricia again?\r\nPeter: _________ I’ve left five messages for her, and she’s never replied."\r\n', 'I haven’t', 'I’d bothered.', 'She doesn’t want to.', 'I can’t be bothered.', 'I can’t be bothered.', 'I can’t be bothered. แปลว่าฉันไม่สามารถรบกวนเขาได้อีก ซึ่งตรงกับรูปประโยค'),
(9, 3, '"William: Can you come round for a meal tonight?\r\nPat: Thanks very much. _______ I haven’t met you for a long time."\r\n', 'I doubt it.', 'I’d love to.', 'SI wish I were.', 'That looks good.\r\n', 'I’d love to.', '\'I\'d love to. แปลว่าอยากทำเช่นนั้นเช่นกันซึ่งมักตามหลังประโยค Thank very much\''),
(9, 4, '"James: What did you think of your brother’s new girlfriend?\r\nJane: _________ I got on with her very well."\r\n', 'She’s fantastic.', 'She looks awful.', 'She’s lost weight.', 'She’s in her thirties.', 'She’s fantastic.', 'Jane ตอบว่า I got on with her very well แสดงว่าไปด้วยกันได้ดี'),
(9, 5, '"Kevin: Hi, Manee (?)________\r\nManee: Hi, I’m great. I’m going to visit my uncle in Songkhla.\r\nAnnouncement: “Ladies & Gentlemen. Attention please! Train 2637, Hualumpong Express, bound for Hadyai will leave at 21.30 hours form platform 3.”\r\nManee: I’m sorry, Kevin. _______ I’ll see you later. There is an announcement about your train also. Bye!"\r\n', 'How’s it like?', 'How about you?', 'How do you do?.', 'How have you been?', 'How have you been?', 'ประโยคที่ใช้ทักทายถามว่าเป็นยังไงบ้างใช้ How have you been?'),
(9, 6, '"Kevin: Hi, Manee ________\r\nManee: Hi, I’m great. I’m going to visit my uncle in Songkhla.\r\nAnnouncement: “Ladies & Gentlemen. Attention please! Train 2637, Hualumpong Express, bound for Hadyai will leave at 21.30 hours form platform 3.”\r\nManee: I’m sorry, Kevin. (?)_______ I’ll see you later. There is an announcement about your train also. Bye!"\r\n', 'Keep your time.', 'Someone is calling me.', 'You can wait for me here.', 'My train is about to leave.\r\n', 'My train is about to leave.', 'เนื่องจากมีเสียงประกาศจากสถานนีว่ามีรถจะออกซึ่งน่าจะเป็นรถไฟของ Manee ดังนั้นจึงต้องตอบว่า My train is about to leave'),
(9, 7, '"Situation: George walks into a furniture store. He only wants to browse.\r\nShop assistant: ___(?)___, sir?\r\nGeorge: No, thanks. ______.\r\nShop assistant: All right. If you need any help, just let me know."\r\n', 'Can I help you', 'Do you want to look around', 'Would you like to buy something', 'Would you mind helping me\r\n', 'Can I help you', 'Can I help you เป็นประโยคคำถามที่นิยมใช้เวลาถามคนที่ต้องการความช่วยเหลือ'),
(9, 8, '"Situation: George walks into a furniture store. He only wants to browse.\r\nShop assistant: ______, sir?\r\nGeorge: No, thanks. ___(?)___.\r\nShop assistant: All right. If you need any help, just let me know."\r\n', 'I don’t need any help', 'It’s my pleasure', 'I’m just looking', 'There’s no need to bother you', 'I’m just looking', '\'George ตอบเป็น No,thanks แสดงว่ายังไม่ต้องารความช่วยเหลือซึ่งควรตอบแบบเหมาะสามคือ I\'m just looking\''),
(9, 9, '"Situation: Jane is trying to calm down her friend, Judy.\r\nJane: Why are you crying, Judy? ___(?)___\r\nJudy: My little kitten, she died last night.\r\nJane: ______"\r\n', 'How have you been?', 'How’s everything?', 'What’s the matter?', 'How sad are you?\r\n', 'What’s the matter?', 'What’s the matter? เป็นประโยคที่ใช้ถามไถ่ความเป็นไปในกรณีที่อยากให้ผู้ตอบเล่าให้ฟัง'),
(9, 10, '"Situation: Jane is trying to calm down her friend, Judy.\r\nJane: Why are you crying, Judy? ______\r\nJudy: My little kitten, she died last night.\r\nJane: ___(?)___"\r\n', 'It doesn’t matter.', 'I’m sorry to hear that.', 'How sad you are!\r\n', 'I wish she wouldn’t die.', 'I’m sorry to hear that.', 'เนื่องจาก ลูกแมวของ Judy ตายจึงควรแสดงความเสียใจจากเรื่องที่ได้ยิน'),
(9, 11, 'Situation: Sandy is hungry. She wants to eat some cookies she bought last night, but she finds that all the cookies are gone.\r\nSandy: Jim, where are the cookies? Don\'t tell me you ate them all! Again!\r\nJim: Yes, I did. ___(?)___. They were so good.\r\nSandy: I thought you didn\'t like cookies.\r\nJim: Well, I don\'t like cookies flavored with chocolate at all. But vanilla cookies are different. ______.\r\n', 'I could eat a horse', 'I’d starve to death', 'It’s none of your business', 'I couldn’t help it', 'I couldn’t help it\r\n', 'I couldn’t help it แปลว่า ช่วยไม่ได้ เพราะ Jim กินคุกกี้ไปจนหมด'),
(9, 12, 'Situation: Sandy is hungry. She wants to eat some cookies she bought last night, but she finds that all the cookies are gone.\r\nSandy: Jim, where are the cookies? Don\'t tell me you ate them all! Again!\r\nJim: Yes, I did. ______. They were so good.\r\nSandy: I thought you didn\'t like cookies.\r\nJim: Well, I don\'t like cookies flavored with chocolate at all. But vanilla cookies are different. ___(?)___.\r\n', 'I love them to death', 'I don’t prefer them', 'They have no flavors at all\r\n', 'I can’t make up my mind', 'I love them to death', 'I love them to death เนื่องจาก Jim บอกว่าไม่ชอบคุกกี้ chocolate แต่สำหรับ vanilla นั้นรักเท่าชีวิต'),
(9, 13, 'Situation: Peter is talking to his friend, Jeff about the assignment.\r\nPeter: Have you handed in the math assignment yet, Jeff?\r\nJeff: No, not yet. Oh, I’m running late. ___(?)____\r\nPeter: ______', 'I must stop talking to you now.', 'Stop saying anything.\r\n.', 'Don’t talk to me now, will you?', 'I’ve got to go to a lecture.\r\n', 'I’ve got to go to a lecture.', 'ประโยคก่อนหน้า Jeff บอกว่าเขากำลังจะสาย แสดงว่าเขาต้องเข้า Lecture'),
(9, 14, 'Situation: Peter is talking to his friend, Jeff about the assignment.\r\nPeter: Have you handed in the math assignment yet, Jeff?\r\nJeff: No, not yet. Oh, I’m running late. ______\r\nPeter: ___(?)____', 'Sorry to keep you. See you later, then.', 'Is that so? Please go now.\r\n', 'Why not? I’ll talk to you again soon.', 'Don’t worry. I think I had better go to the lecture, too.,\r\n', 'Sorry to keep you. See you later, then.', 'หลังจากที่ Peter รู้ว่า Jeff กำลังไปสาย เขาจึงขอโทษ'),
(9, 15, '"Situation: Nell is on the train.\r\nMan: ___(?)___\r\nNell: ______ … Oh no, I’m sorry."\r\n', 'Move to another seat. This is mine.', 'Whose seat are you in now?', 'How come you’re sitting in the wrong seat!', 'Excuse me, I think you’ve taken my seat.\r\n', 'Excuse me, I think you’ve taken my seat.\r\n', 'การพูดกับคนที่ไม่รู้จักหรือคนแปลกหน้าควรใช้คำว่า Excuse me'),
(9, 16, '"Situation: Nell is on the train.\r\nMan: ______\r\nNell: ___(?)___ … Oh no, I’m sorry."\r\n', 'No, it’s my seat. Please find another one.', 'Are you sure you are all right?\r\n', 'I don’t think so, but let me check my ticket.', 'I’m sure you’re wrong. Please take the other one.', 'I don’t think so, but let me check my ticket.\r\n', 'เป็นคำตอบที่เหมาะสมที่สุดในการสนทนากับคนแปลกหน้า'),
(9, 17, '___(?)___ Emily Dickinson is now a well-known American poet, only seven of her poems ______ while she was alive.\r\n', 'Although', 'Because', 'Despite', 'When', 'Although\r\n', 'จาก only seven แสดงว่า Emily Dickinson มีนิยายมากกว่านั้น จึงควรใช้ Although ที่แปลว่าแม้ว่า'),
(9, 18, '______ Emily Dickinson is now a well-known American poet, only seven of her poems ___(?)___ while she was alive.\r\n', 'publishing', 'to publish', 'have published', 'were published', 'were published\r\n', 'จาก while she was alive แสดงว่า Emily เสียชีวิตไปแล้ว จึงต้องใช้ Past Cont were + v.2'),
(9, 19, 'The term robot, ___(?)___ meaning labor, _______ to machines in the 1920s.\r\n', 'which actually a Czech word', 'which is actually a Czech word', 'is actual a Czech word\r\n', 'that is actually a Czech word', 'which is actually a Czech word\r\n', 'which is actually a Czech word เป็นประโยคเดียวที่ถูก Grammar'),
(9, 20, 'The term robot, ______ meaning labor, ___(?)___ to machines in the 1920s.\r\n', 'first applied', 'first applying', 'was first applying', 'was first applied.', 'was first applied.\r\n', 'in 1920s แสดงให้เห็นว่าผ่านมาแล้วต้องใช้ was first applied'),
(10, 1, '"Anyone ___(?)___ in a strong wind knows it is ______ than against it."', 'rows a boat', 'rowing a boat', 'who row a boat', 'rowed a boat', 'rowing a boat', 'in a strong wind แสดงว่า เป็นการกระทำที่ทำอยู่ ต้องใช้ v.ing'),
(10, 2, '"Anyone ______ in a strong wind knows it is ___(?)___ than against it."', 'very easy to go with the wind', 'much easy going with the wind', 'much easier to go with the wind', 'very easier to go with the wind', 'much easier to go with the wind', 'than เป็นการเปรียบที่ ต้องใช้ mush กับ easier'),
(10, 3, '___(?)___ have ______ plastic soda bottles into polyester fabric.\r\n', 'Recent engineering developments', 'Recent engineer developments', 'Recently engineer developments', 'TRecently engineering development\r\n', 'Recent engineering developments', 'Recent แสดงว่าเป็นการกระทำที่พึ่งเกิดขึ้น ต้องใช้ V.ing'),
(10, 4, '______ have ___(?)___ plastic soda bottles into polyester fabric.\r\n', 'made possible to recycle', 'made it possible to recycle', 'made it possible of recycling', 'made it possible recycling', 'made it possible to recycle', 'made it possible to recycle ตรงตามหลัก Grammar'),
(10, 5, 'In Florida, when the temperature drops below freezing, citrus growers ___(?)___ by ______.\r\n', 'keep young trees warm', 'keep young trees warmly', 'keep young trees are warm', 'keep young trees that are warm', 'keep young trees warm', 'keep young trees warm เป็นประโยคที่ถูกต้องตามหลักการใช้'),
(10, 6, 'In Florida, when the temperature drops below freezing, citrus growers ______ by ___(?)___.\r\n', 'constant showering them with water', 'constantly showering them with water', 'constantly shower them by water', 'constant to shower them with water\r\n', 'constantly showering them with water', 'constantly showering them with water เป็นประโยคที่ถูกต้องตามหลักการใช้'),
(10, 7, '"Situation: George walks into a furniture store. He only wants to browse.\r\nShop assistant: ___(?)___, sir?\r\nGeorge: No, thanks. ______.\r\nShop assistant: All right. If you need any help, just let me know."\r\n', 'Can I help you', 'Do you want to look around', 'Would you like to buy something', 'Would you mind helping me\r\n', 'Can I help you', 'Can I help you เป็นประโยคคำถามที่นิยมใช้เวลาถามคนที่ต้องการความช่วยเหลือ'),
(10, 8, '"Situation: George walks into a furniture store. He only wants to browse.\r\nShop assistant: ______, sir?\r\nGeorge: No, thanks. ___(?)___.\r\nShop assistant: All right. If you need any help, just let me know."\r\n', 'I don’t need any help', 'It’s my pleasure', 'I’m just looking', 'There’s no need to bother you', 'I’m just looking', '\'George ตอบเป็น No,thanks แสดงว่ายังไม่ต้องารความช่วยเหลือซึ่งควรตอบแบบเหมาะสามคือ I\'m just looking\''),
(10, 9, '"Situation: Jane is trying to calm down her friend, Judy.\r\nJane: Why are you crying, Judy? ___(?)___\r\nJudy: My little kitten, she died last night.\r\nJane: ______"\r\n', 'How have you been?', 'How’s everything?', 'What’s the matter?', 'How sad are you?\r\n', 'What’s the matter?', 'What’s the matter? เป็นประโยคที่ใช้ถามไถ่ความเป็นไปในกรณีที่อยากให้ผู้ตอบเล่าให้ฟัง'),
(10, 10, '"Situation: Jane is trying to calm down her friend, Judy.\r\nJane: Why are you crying, Judy? ______\r\nJudy: My little kitten, she died last night.\r\nJane: ___(?)___"\r\n', 'It doesn’t matter.', 'I’m sorry to hear that.', 'How sad you are!\r\n', 'I wish she wouldn’t die.', 'I’m sorry to hear that.', 'เนื่องจาก ลูกแมวของ Judy ตายจึงควรแสดงความเสียใจจากเรื่องที่ได้ยิน'),
(10, 11, '“The best substitute for brains is silence.” This means that……….\r\n', 'you should remain quiet even when you know the correct answer\r\n', 'it is better to be smart than to be quiet', 'when you are quiet, people will think you don’t know anything\r\n', 'if you don’t know the answer, keep quiet.', 'if you don’t know the answer, keep quiet.\r\n', 'Subsitute แปลว่า ตัวแทน ดังนั้นทั้งประโยคจึงแปว่า ตัวแทนที่ดีที่สุดของสมองคือความเงียบ'),
(10, 12, '"Reach for the moon because even if you miss it, you will still be among the stars.” This teachers us that we should….."', 'enjoy air travel', 'set our goals high', 'become a pilot\r\n', 'study astronomy', 'set our goals high', 'จากโจทย์แปลว่า ถ้าไปถึงดวงจันทร์ต่อให้พลาดก็ยังเป็นดวงดาว หมายความว่าถ้าตั้งเป้าหมายสูงยังไงก็ได้ผลที่ดี'),
(10, 13, '“We must believe in luck. For how else can we explain the success of those we don’t like?” This means that….\r\n', 'we don’t like people who are lucky', 'we don’t like people who are successful\r\n', 'if people we don’t like are successful, we say that they are just lucky', 'we must not like people whose success is based on luck\r\n', 'if people we don’t like are successful, we say that they are just lucky', 'คนที่ไม่เคยประสบความสำเร็จก็จะว่าคนที่ประสบความสำเร็จว่าแค่โชคดี'),
(10, 14, '“No one should approach the temple of science with the soul of a money changer.” This is advice for those who would like to become……', 'bankers', 'monks', 'scientists', 'architects', 'scientists', 'จากประโยคเปรียบเปรยว่า วัดของวิทยาศาสตร์ที่มีวิญญาณเป็นตัวเปลี่ยนค่าเงินคือนักวิทยาศาสตร์'),
(10, 15, 'The government has ___ a new energy-saving campaign to solve the country’s energy crisis.\r\n', 'noticed', 'emerged', 'installed', 'launched', 'launched', 'รัฐบาลเป็นหน่วยงาน ดังนั้นจึงต้องใช้คำว่า launched'),
(10, 16, 'Sally used to be terribly shy, but a year abroad has completely ___ her.\r\n', 'criticized', 'protested', 'transformed', 'renounced', 'transformed', 'transformed แปลว่าเปลี่ยนแปลง ที่ต้องใช้เพราะดูได้จาก but'),
(10, 17, 'For years, people thought the picture was a ___ Van Gogh; nevertheless, in fact it is a fake one.\r\n', 'like', 'right', 'genuine', 'credible', 'genuine', 'จากประโยค in fact it is a fake one แสดงว่า ความจริงที่รู้กันคือมีของแท้ genuine แปลว่าของแท้'),
(10, 18, '"The residents in the area of the industrial estate claimed that the smoke and smell from the factory were unpleasant and ___ to breath.\r\n"', 'infectious', 'beneficial', 'influential', 'hazardous', 'hazardous', 'hazardous แปลว่าเสี่ยงอันตราย ซึ่งบุหรี่ส่งผลอันตราย'),
(10, 19, 'Cremation is common in Asia; whereas, ___ is in Europe.\r\n', 'burial', 'burner', 'explosion', 'excavation', 'burial', 'burial แปลว่า พิธีฝ่งศพ Cremation แปลว่า พิธีเผาศพ'),
(10, 20, 'The judge’s decision is final, ___. Not to do so would be treason.\r\n', 'and we mist abide by it', 'nor must we agree with it', 'however we are desirous of it', 'we mist not be superior from it\r\n', 'and we mist abide by it', 'and we mist abide by it แปลว่าและเราหมกมุ่นอยู่กับมัน ซึ่งเหมาะกับ คนที่รอฟังคำตัดสินของศาล');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `exam`
--
ALTER TABLE `exam`
  ADD KEY `fk_exam_quiz1_idx` (`quiz_id`);

--
-- Constraints for dumped tables
--

--
-- Constraints for table `exam`
--
ALTER TABLE `exam`
  ADD CONSTRAINT `fk_exam_quiz1` FOREIGN KEY (`quiz_id`) REFERENCES `quiz` (`quiz_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
